
version: '2.4'

networks:
  mysql_net:

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      PMA_HOST: dockerhost
    extra_hosts:
      - "dockerhost:172.20.0.1"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    extra_hosts:
      - "dockerhost:172.20.0.1"


networks:
  default:
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.0/16
        gateway: 172.20.0.1
