version: '2.4'

networks:
  mysql_net:

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    command: --default-authentication-plugin=mysql_native_password --collation-server=utf8mb4_unicode_ci --character-set-server=utf8mb4
    volumes:
     - /var/lib/mysql/my_db/:/var/lib/mysql/
    restart: always
    mem_limit: 700M
    mem_reservation: 100M
    environment:
      MYSQL_ROOT_PASSWORD: root_pass@123
      MYSQL_DATABASE: my_db
      MYSQL_USER: radhe
      MYSQL_PASSWORD: password@123
    ports:
      - 3307:3306
    expose:
      - 3306
    networks:
      - mysql_net

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql_db
      MYSQL_ROOT_PASSWORD: root_pass
    networks:
      - mysql_net

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - mysql_net
